### ISSUE TITLE
Default year/month in the CLI not corresponding to day of month in the data

### ISSUE THREAD

**Issue by RoryPTB** [wmo-im/synop2bufr#23]
When using the default year and month in the CLI, there is a possibility that it is not compatible with the day of the month found in the data. For example, if the day of the month is 31, then using the default year/month right now gives a date of 31st June 2023, which causes an error.
This can either be resolved by doing a validation of the proposed date before encoding, or by scrapping the default year/month altogether.

**Comment by tomkralidis** [comment]
Option (assumes year/month passed via CLI or API):
- get day of month from SYNOP
- test for a valid date:

```python
from datetime import 

year = 2023
month = 6
day = 31

try:
    ymd = datetime(year, month, day)
except ValueError as err:
    msg = f'Invalid date: {err}'
    LOGGER.error(msg)
    raise RuntimeError(msg)
```

Related: https://github.com/wmo-im/synop2bufr/pull/27 (forces year/month from CLI)

**Comment by david-i-berry** [comment]
Closed by https://github.com/wmo-im/synop2bufr/pull/27
